import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import * as XLSX from 'xlsx'

const LIME   = [200, 255, 0]
const DARK   = [22, 22, 22]
const DARK2  = [30, 30, 30]
const WHITE  = [255, 255, 255]
const GREY   = [180, 180, 180]
const LGREY  = [40, 40, 40]

// ── Shared PDF header/footer ──────────────────────────────────
function addPDFHeader(doc, title, period = '') {
  const w = doc.internal.pageSize.getWidth()
  doc.setFillColor(...DARK)
  doc.rect(0, 0, w, 22, 'F')
  doc.setFillColor(...LIME)
  doc.rect(0, 0, 4, 22, 'F')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(13)
  doc.setTextColor(...LIME)
  doc.text('CFO-X', 10, 14)
  doc.setTextColor(...WHITE)
  doc.setFontSize(11)
  doc.text(title.toUpperCase(), 36, 14)
  if (period) {
    doc.setFontSize(8)
    doc.setTextColor(...GREY)
    doc.text(`Period: ${period}`, w - 10, 14, { align: 'right' })
  }
}

function addPDFFooter(doc, businessName = 'Your Business') {
  const pageCount = doc.internal.getNumberOfPages()
  const w = doc.internal.pageSize.getWidth()
  const h = doc.internal.pageSize.getHeight()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFillColor(...DARK)
    doc.rect(0, h - 14, w, 14, 'F')
    doc.setFontSize(7)
    doc.setTextColor(...GREY)
    doc.text(`CONFIDENTIAL — Generated by CFO-X  |  ${businessName}  |  ${new Date().toLocaleDateString()}`, 10, h - 5)
    doc.text(`Page ${i} of ${pageCount}`, w - 10, h - 5, { align: 'right' })
    // Watermark
    doc.setTextColor(255, 255, 255, 0.04)
    doc.setFontSize(28)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(60, 60, 60)
    doc.text('CONFIDENTIAL', w / 2, h / 2, { align: 'center', angle: 45 })
  }
}

function tableStyles() {
  return {
    headStyles: { fillColor: DARK, textColor: LIME, fontStyle: 'bold', fontSize: 8 },
    bodyStyles: { fillColor: DARK2, textColor: WHITE, fontSize: 8 },
    alternateRowStyles: { fillColor: [26, 26, 26] },
    styles: { lineColor: LGREY, lineWidth: 0.2 },
  }
}

// ── P&L ───────────────────────────────────────────────────────
export function generatePLPDF(businessName, period) {
  const doc = new jsPDF()
  addPDFHeader(doc, 'Profit & Loss Statement', period)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(...GREY)
  doc.text(`${businessName}   ·   Generated ${new Date().toLocaleDateString()}`, 10, 30)

  autoTable(doc, {
    startY: 36,
    head: [['Category', 'This Period', 'Prior Period', 'Change']],
    body: [
      ['REVENUE', '', '', ''],
      ['Product Sales', '$38,400', '$35,200', '+9.1%'],
      ['Service Revenue', '$12,800', '$11,500', '+11.3%'],
      ['Other Income', '$4,000', '$3,800', '+5.3%'],
      ['TOTAL REVENUE', '$55,200', '$50,500', '+9.3%'],
      ['', '', '', ''],
      ['COST OF GOODS SOLD', '', '', ''],
      ['Direct Costs', '$17,112', '$15,655', '+9.3%'],
      ['GROSS PROFIT', '$38,088', '$34,845', '+9.3%'],
      ['Gross Margin', '69%', '69%', '—'],
      ['', '', '', ''],
      ['OPERATING EXPENSES', '', '', ''],
      ['Payroll & Benefits', '$14,500', '$13,800', '+5.1%'],
      ['Rent & Utilities', '$3,200', '$3,200', '0%'],
      ['Software & Tools', '$1,800', '$1,650', '+9.1%'],
      ['Marketing & Ads', '$2,100', '$1,900', '+10.5%'],
      ['Insurance', '$650', '$650', '0%'],
      ['Miscellaneous', '$250', '$300', '-16.7%'],
      ['TOTAL OPERATING EXP', '$22,500', '$21,500', '+4.7%'],
      ['', '', '', ''],
      ['NET OPERATING INCOME', '$15,588', '$13,345', '+16.8%'],
      ['Interest Expense', '$1,100', '$1,100', '0%'],
      ['NET PROFIT', '$14,488', '$12,245', '+18.3%'],
      ['Net Margin', '26.2%', '24.2%', '+2.0pp'],
    ],
    ...tableStyles(),
    didParseCell(data) {
      if (['TOTAL REVENUE','GROSS PROFIT','NET OPERATING INCOME','NET PROFIT'].includes(data.cell.raw)) {
        data.cell.styles.fontStyle = 'bold'
        data.cell.styles.textColor = LIME
      }
      if (data.cell.raw === '') data.cell.styles.fillColor = [20, 20, 20]
    },
  })

  addPDFFooter(doc, businessName)
  doc.save(`PL-Statement-${period.replace(/\s/g,'-')}.pdf`)
}

export function generatePLCSV(period) {
  const rows = [
    ['Category','This Period','Prior Period','Change'],
    ['REVENUE','','',''],
    ['Product Sales','$38,400','$35,200','+9.1%'],
    ['Service Revenue','$12,800','$11,500','+11.3%'],
    ['Other Income','$4,000','$3,800','+5.3%'],
    ['TOTAL REVENUE','$55,200','$50,500','+9.3%'],
    ['','','',''],
    ['COST OF GOODS SOLD','','',''],
    ['Direct Costs','$17,112','$15,655','+9.3%'],
    ['GROSS PROFIT','$38,088','$34,845','+9.3%'],
    ['OPERATING EXPENSES','','',''],
    ['Payroll & Benefits','$14,500','$13,800','+5.1%'],
    ['Rent & Utilities','$3,200','$3,200','0%'],
    ['Software & Tools','$1,800','$1,650','+9.1%'],
    ['Marketing & Ads','$2,100','$1,900','+10.5%'],
    ['Insurance','$650','$650','0%'],
    ['Miscellaneous','$250','$300','-16.7%'],
    ['TOTAL OPERATING EXP','$22,500','$21,500','+4.7%'],
    ['NET PROFIT','$14,488','$12,245','+18.3%'],
  ]
  const csv = rows.map(r => r.join(',')).join('\n')
  downloadText(csv, `PL-Statement-${period.replace(/\s/g,'-')}.csv`, 'text/csv')
}

export function generatePLExcel(period) {
  const data = [
    ['Profit & Loss Statement', '', `Period: ${period}`, `Generated: ${new Date().toLocaleDateString()}`],
    [],
    ['Category', 'This Period', 'Prior Period', 'Change'],
    ['REVENUE'],
    ['Product Sales', 38400, 35200, '9.1%'],
    ['Service Revenue', 12800, 11500, '11.3%'],
    ['Other Income', 4000, 3800, '5.3%'],
    ['TOTAL REVENUE', 55200, 50500, '9.3%'],
    [],
    ['COST OF GOODS SOLD'],
    ['Direct Costs', 17112, 15655, '9.3%'],
    ['GROSS PROFIT', 38088, 34845, '9.3%'],
    [],
    ['OPERATING EXPENSES'],
    ['Payroll & Benefits', 14500, 13800, '5.1%'],
    ['Rent & Utilities', 3200, 3200, '0%'],
    ['Software & Tools', 1800, 1650, '9.1%'],
    ['Marketing & Ads', 2100, 1900, '10.5%'],
    ['Insurance', 650, 650, '0%'],
    ['Miscellaneous', 250, 300, '-16.7%'],
    ['TOTAL OPERATING EXP', 22500, 21500, '4.7%'],
    [],
    ['NET PROFIT', 14488, 12245, '18.3%'],
  ]
  makeXLSX(data, 'P&L Statement', `PL-Statement-${period.replace(/\s/g,'-')}.xlsx`, [28, 16, 16, 10])
}

// ── Cash Flow ─────────────────────────────────────────────────
export function generateCashFlowPDF(businessName, period) {
  const doc = new jsPDF()
  addPDFHeader(doc, 'Cash Flow Statement', period)
  doc.setFontSize(9); doc.setTextColor(...GREY)
  doc.text(`${businessName}   ·   Generated ${new Date().toLocaleDateString()}`, 10, 30)

  autoTable(doc, {
    startY: 36,
    head: [['Activity', 'Amount', 'Notes']],
    body: [
      ['OPERATING ACTIVITIES', '', ''],
      ['Net Income', '$14,488', ''],
      ['Depreciation', '$750', 'Non-cash add-back'],
      ['Accounts Receivable Change', '-$2,800', 'Increase in AR'],
      ['Accounts Payable Change', '+$1,200', 'Increase in AP'],
      ['Inventory Change', '-$500', 'Inventory build'],
      ['Net Cash from Operations', '$13,138', ''],
      ['', '', ''],
      ['INVESTING ACTIVITIES', '', ''],
      ['Equipment Purchase', '-$5,000', 'New machinery'],
      ['Net Cash from Investing', '-$5,000', ''],
      ['', '', ''],
      ['FINANCING ACTIVITIES', '', ''],
      ['Loan Repayment', '-$1,100', 'Monthly debt service'],
      ['Net Cash from Financing', '-$1,100', ''],
      ['', '', ''],
      ['NET CHANGE IN CASH', '+$7,038', ''],
      ['Beginning Cash Balance', '$39,962', ''],
      ['ENDING CASH BALANCE', '$47,000', ''],
    ],
    ...tableStyles(),
    didParseCell(data) {
      if (['Net Cash from Operations','Net Cash from Investing','Net Cash from Financing','NET CHANGE IN CASH','ENDING CASH BALANCE'].includes(data.cell.raw)) {
        data.cell.styles.fontStyle = 'bold'
        data.cell.styles.textColor = LIME
      }
    },
  })
  addPDFFooter(doc, businessName)
  doc.save(`Cash-Flow-${period.replace(/\s/g,'-')}.pdf`)
}

export function generateCashFlowExcel(period) {
  const data = [
    ['Cash Flow Statement', '', `Period: ${period}`],
    [],
    ['Activity', 'Amount', 'Notes'],
    ['OPERATING ACTIVITIES'],
    ['Net Income', 14488, ''],
    ['Depreciation', 750, 'Non-cash'],
    ['AR Change', -2800, ''],
    ['AP Change', 1200, ''],
    ['Inventory Change', -500, ''],
    ['Net Cash from Operations', 13138, ''],
    [],
    ['INVESTING ACTIVITIES'],
    ['Equipment Purchase', -5000, ''],
    ['Net Cash from Investing', -5000, ''],
    [],
    ['FINANCING ACTIVITIES'],
    ['Loan Repayment', -1100, ''],
    ['Net Cash from Financing', -1100, ''],
    [],
    ['NET CHANGE IN CASH', 7038, ''],
    ['Beginning Cash', 39962, ''],
    ['ENDING CASH BALANCE', 47000, ''],
  ]
  makeXLSX(data, 'Cash Flow', `Cash-Flow-${period.replace(/\s/g,'-')}.xlsx`, [30, 16, 24])
}

export function generateCashFlowCSV(period) {
  const rows = [
    ['Activity','Amount','Notes'],
    ['Net Income','$14,488',''],
    ['Depreciation','$750','Non-cash'],
    ['Net Cash from Operations','$13,138',''],
    ['Equipment Purchase','-$5,000',''],
    ['Loan Repayment','-$1,100',''],
    ['NET CHANGE IN CASH','+$7,038',''],
    ['ENDING CASH BALANCE','$47,000',''],
  ]
  downloadText(rows.map(r=>r.join(',')).join('\n'), `Cash-Flow-${period.replace(/\s/g,'-')}.csv`, 'text/csv')
}

// ── Balance Sheet ─────────────────────────────────────────────
export function generateBalanceSheetPDF(businessName, period) {
  const doc = new jsPDF()
  addPDFHeader(doc, 'Balance Sheet', period)
  doc.setFontSize(9); doc.setTextColor(...GREY)
  doc.text(`${businessName}   ·   Generated ${new Date().toLocaleDateString()}`, 10, 30)

  autoTable(doc, {
    startY: 36,
    head: [['Item', 'Amount']],
    body: [
      ['ASSETS', ''],
      ['Cash & Equivalents', '$47,000'],
      ['Accounts Receivable', '$28,500'],
      ['Inventory', '$12,000'],
      ['Equipment', '$45,000'],
      ['TOTAL ASSETS', '$132,500'],
      ['', ''],
      ['LIABILITIES', ''],
      ['Accounts Payable', '$8,200'],
      ['Short-term Debt', '$15,000'],
      ['Long-term Debt', '$35,000'],
      ['TOTAL LIABILITIES', '$58,200'],
      ['', ''],
      ['EQUITY', ''],
      ["Owner's Equity", '$74,300'],
      ['TOTAL LIABILITIES + EQUITY', '$132,500'],
    ],
    ...tableStyles(),
    didParseCell(data) {
      if (['TOTAL ASSETS','TOTAL LIABILITIES','TOTAL LIABILITIES + EQUITY'].includes(data.cell.raw)) {
        data.cell.styles.fontStyle = 'bold'
        data.cell.styles.textColor = LIME
      }
      if (['ASSETS','LIABILITIES','EQUITY'].includes(data.cell.raw)) {
        data.cell.styles.fontStyle = 'bold'
        data.cell.styles.textColor = [...GREY]
      }
    },
    columnStyles: { 1: { halign: 'right' } },
  })
  addPDFFooter(doc, businessName)
  doc.save(`Balance-Sheet-${period.replace(/\s/g,'-')}.pdf`)
}

export function generateBalanceSheetExcel(period) {
  const data = [
    ['Balance Sheet', `Period: ${period}`],
    [],
    ['Item', 'Amount'],
    ['ASSETS'],
    ['Cash & Equivalents', 47000],
    ['Accounts Receivable', 28500],
    ['Inventory', 12000],
    ['Equipment', 45000],
    ['TOTAL ASSETS', 132500],
    [],
    ['LIABILITIES'],
    ['Accounts Payable', 8200],
    ['Short-term Debt', 15000],
    ['Long-term Debt', 35000],
    ['TOTAL LIABILITIES', 58200],
    [],
    ['EQUITY'],
    ["Owner's Equity", 74300],
    ['TOTAL LIABILITIES + EQUITY', 132500],
  ]
  makeXLSX(data, 'Balance Sheet', `Balance-Sheet-${period.replace(/\s/g,'-')}.xlsx`, [30, 16])
}

export function generateBalanceSheetCSV(period) {
  const rows = [
    ['Item','Amount'],
    ['Cash & Equivalents','$47,000'],
    ['Accounts Receivable','$28,500'],
    ['Inventory','$12,000'],
    ['Equipment','$45,000'],
    ['TOTAL ASSETS','$132,500'],
    ['Accounts Payable','$8,200'],
    ['Short-term Debt','$15,000'],
    ['Long-term Debt','$35,000'],
    ['TOTAL LIABILITIES','$58,200'],
    ["Owner's Equity",'$74,300'],
    ['TOTAL LIABILITIES + EQUITY','$132,500'],
  ]
  downloadText(rows.map(r=>r.join(',')).join('\n'), `Balance-Sheet-${period.replace(/\s/g,'-')}.csv`, 'text/csv')
}

// ── Executive Summary ─────────────────────────────────────────
export function generateExecutiveSummaryPDF(businessName, profile) {
  const doc = new jsPDF()
  const w = doc.internal.pageSize.getWidth()
  addPDFHeader(doc, 'Executive Summary', 'Current Period')

  doc.setFontSize(9); doc.setTextColor(...GREY)
  doc.text(`${businessName}   ·   Generated ${new Date().toLocaleDateString()}`, 10, 30)

  // Business Overview block
  doc.setFillColor(...LGREY)
  doc.rect(10, 34, w - 20, 28, 'F')
  doc.setFont('helvetica', 'bold'); doc.setFontSize(10); doc.setTextColor(...LIME)
  doc.text('BUSINESS OVERVIEW', 14, 42)
  doc.setFont('helvetica', 'normal'); doc.setFontSize(8); doc.setTextColor(...WHITE)
  doc.text(`Business: ${businessName}`, 14, 49)
  doc.text(`Industry: ${profile?.industry || 'Technology'}   |   Years in Operation: 3`, 14, 55)
  doc.text(`Goal: ${profile?.goal || 'Grow Revenue'}`, 14, 61)

  // KPI table
  autoTable(doc, {
    startY: 68,
    head: [['KPI', 'Value', 'Trend']],
    body: [
      ['Monthly Revenue', '$55,200', '+9.3% MoM'],
      ['Monthly Expenses', '$22,500', '+4.7% MoM'],
      ['Net Profit', '$14,488', '+18.3% MoM'],
      ['Net Margin', '26.2%', '+2.0pp'],
      ['Cash Balance', '$47,000', '+$7,038'],
      ['Monthly Burn Rate', '$22,500', 'Stable'],
      ['Cash Runway', '25+ months', 'Healthy'],
      ['Growth Rate (MoM)', '+8.7%', 'Accelerating'],
    ],
    ...tableStyles(),
    didParseCell(data) {
      if (data.row.index % 2 === 0 && data.section === 'body') {
        if (String(data.cell.raw).startsWith('+')) data.cell.styles.textColor = LIME
      }
    },
  })

  // Funding use section
  const y = doc.lastAutoTable.finalY + 8
  doc.setFont('helvetica', 'bold'); doc.setFontSize(9); doc.setTextColor(...LIME)
  doc.text('PROPOSED USE OF FUNDS', 10, y)
  doc.setFont('helvetica', 'normal'); doc.setFontSize(8); doc.setTextColor(...WHITE)
  const uses = [
    '• 40% — Marketing & Customer Acquisition',
    '• 30% — Inventory & Operations Expansion',
    '• 20% — Technology Infrastructure',
    '• 10% — Working Capital Reserve',
  ]
  uses.forEach((line, i) => doc.text(line, 12, y + 7 + i * 6))

  // AI Recommendation
  const y2 = y + 38
  doc.setFillColor(...LGREY)
  doc.rect(10, y2, w - 20, 30, 'F')
  doc.setFillColor(...LIME)
  doc.rect(10, y2, 3, 30, 'F')
  doc.setFont('helvetica', 'bold'); doc.setFontSize(8); doc.setTextColor(...LIME)
  doc.text('CFO-X AI ASSESSMENT', 17, y2 + 7)
  doc.setFont('helvetica', 'normal'); doc.setFontSize(7.5); doc.setTextColor(...WHITE)
  const aiText = `${businessName} demonstrates strong financial health with a 26.2% net margin and consistent MoM revenue growth of 8.7%. Cash runway exceeds 25 months, indicating excellent liquidity. The debt-to-equity ratio of 0.78 is within acceptable lending thresholds. This business is well-positioned for a growth loan or line of credit.`
  const lines = doc.splitTextToSize(aiText, w - 30)
  doc.text(lines, 17, y2 + 15)

  // 12-month projection
  autoTable(doc, {
    startY: y2 + 36,
    head: [['Month', 'Projected Revenue', 'Projected Profit']],
    body: Array.from({ length: 12 }, (_, i) => {
      const rev = Math.round(55200 * Math.pow(1.087, i + 1))
      const profit = Math.round(rev * 0.262)
      const date = new Date(); date.setMonth(date.getMonth() + i + 1)
      return [date.toLocaleDateString('en-US', { month: 'short', year: 'numeric' }), `$${rev.toLocaleString()}`, `$${profit.toLocaleString()}`]
    }),
    ...tableStyles(),
    columnStyles: { 1: { halign: 'right' }, 2: { halign: 'right' } },
  })

  addPDFFooter(doc, businessName)
  doc.save('Executive-Summary.pdf')
}

// ── Revenue Projections ───────────────────────────────────────
export function generateProjectionsPDF(businessName) {
  const doc = new jsPDF()
  addPDFHeader(doc, 'Revenue Projections — 12 Month', 'Forward-Looking')
  doc.setFontSize(9); doc.setTextColor(...GREY)
  doc.text(`${businessName}   ·   Base growth rate: +8.7% MoM`, 10, 30)

  const rows = Array.from({ length: 12 }, (_, i) => {
    const date = new Date(); date.setMonth(date.getMonth() + i + 1)
    const base = Math.round(55200 * Math.pow(1.087, i + 1))
    const cons = Math.round(55200 * Math.pow(1.04, i + 1))
    const opt  = Math.round(55200 * Math.pow(1.14, i + 1))
    return [
      date.toLocaleDateString('en-US', { month: 'short', year: 'numeric' }),
      `$${cons.toLocaleString()}`,
      `$${base.toLocaleString()}`,
      `$${opt.toLocaleString()}`,
    ]
  })

  autoTable(doc, {
    startY: 36,
    head: [['Month', 'Conservative (+4%)', 'Base (+8.7%)', 'Optimistic (+14%)']],
    body: rows,
    ...tableStyles(),
    columnStyles: { 1: { halign: 'right' }, 2: { halign: 'right', textColor: LIME }, 3: { halign: 'right' } },
  })
  addPDFFooter(doc, businessName)
  doc.save('Revenue-Projections-12mo.pdf')
}

export function generateProjectionsExcel() {
  const header = ['Month', 'Conservative (+4%)', 'Base (+8.7%)', 'Optimistic (+14%)']
  const rows = Array.from({ length: 12 }, (_, i) => {
    const date = new Date(); date.setMonth(date.getMonth() + i + 1)
    return [
      date.toLocaleDateString('en-US', { month: 'short', year: 'numeric' }),
      Math.round(55200 * Math.pow(1.04, i + 1)),
      Math.round(55200 * Math.pow(1.087, i + 1)),
      Math.round(55200 * Math.pow(1.14, i + 1)),
    ]
  })
  makeXLSX([header, ...rows], 'Projections', 'Revenue-Projections-12mo.xlsx', [16, 20, 20, 20])
}

// ── Debt Schedule ─────────────────────────────────────────────
export function generateDebtSchedulePDF(businessName) {
  const doc = new jsPDF()
  addPDFHeader(doc, 'Debt Schedule', 'Current')
  doc.setFontSize(9); doc.setTextColor(...GREY)
  doc.text(`${businessName}   ·   Generated ${new Date().toLocaleDateString()}`, 10, 30)

  autoTable(doc, {
    startY: 36,
    head: [['Creditor / Loan', 'Original', 'Balance', 'Rate', 'Monthly Pmt', 'Maturity']],
    body: [
      ['Business Line of Credit', '$20,000', '$15,000', '6.5% APR', '$450', 'Revolving'],
      ['Equipment Loan', '$40,000', '$35,000', '5.2% APR', '$650', '48 mo remaining'],
      ['TOTAL DEBT SERVICE', '', '$50,000', '', '$1,100/mo', ''],
    ],
    ...tableStyles(),
    didParseCell(data) {
      if (data.cell.raw === 'TOTAL DEBT SERVICE') {
        data.cell.styles.fontStyle = 'bold'; data.cell.styles.textColor = LIME
      }
    },
  })

  // Summary box
  const y = doc.lastAutoTable.finalY + 10
  doc.setFillColor(...LGREY)
  doc.rect(10, y, 80, 28, 'F')
  doc.setFont('helvetica', 'bold'); doc.setFontSize(8); doc.setTextColor(...LIME)
  doc.text('DEBT SUMMARY', 14, y + 8)
  doc.setFont('helvetica', 'normal'); doc.setFontSize(8); doc.setTextColor(...WHITE)
  doc.text('Total Monthly Service: $1,100', 14, y + 15)
  doc.text('Debt-to-Revenue Ratio: 2.0%', 14, y + 21)
  doc.text('Debt-to-Equity Ratio: 0.78', 14, y + 27)

  addPDFFooter(doc, businessName)
  doc.save('Debt-Schedule.pdf')
}

export function generateDebtScheduleExcel() {
  const data = [
    ['Debt Schedule', `Generated: ${new Date().toLocaleDateString()}`],
    [],
    ['Creditor', 'Original Amount', 'Current Balance', 'Interest Rate', 'Monthly Payment', 'Maturity'],
    ['Business Line of Credit', 20000, 15000, '6.5%', 450, 'Revolving'],
    ['Equipment Loan', 40000, 35000, '5.2%', 650, '48 mo remaining'],
    [],
    ['TOTAL', 60000, 50000, '', 1100, ''],
  ]
  makeXLSX(data, 'Debt Schedule', 'Debt-Schedule.xlsx', [28, 16, 16, 14, 16, 18])
}

// ── Expense Budget ────────────────────────────────────────────
export function generateExpenseBudgetPDF(businessName) {
  const doc = new jsPDF()
  addPDFHeader(doc, 'Expense Budget — Planned vs Actual', 'Current Month')
  doc.setFontSize(9); doc.setTextColor(...GREY)
  doc.text(`${businessName}   ·   Generated ${new Date().toLocaleDateString()}`, 10, 30)

  autoTable(doc, {
    startY: 36,
    head: [['Category', 'Budget', 'Actual', 'Variance', 'Status']],
    body: [
      ['Payroll & Benefits', '$14,500', '$14,500', '$0', '✓ On Budget'],
      ['Rent & Utilities', '$3,200', '$3,200', '$0', '✓ On Budget'],
      ['Software & Tools', '$2,000', '$1,800', '+$200', '✓ Under'],
      ['Marketing & Ads', '$2,500', '$2,100', '+$400', '✓ Under'],
      ['Insurance', '$650', '$650', '$0', '✓ On Budget'],
      ['Travel & Entertainment', '$500', '$320', '+$180', '✓ Under'],
      ['Office Supplies', '$300', '$250', '+$50', '✓ Under'],
      ['Miscellaneous', '$500', '$250', '+$250', '✓ Under'],
      ['TOTAL OPERATING EXP', '$24,150', '$23,070', '+$1,080', '✓ Under Budget'],
    ],
    ...tableStyles(),
    didParseCell(data) {
      if (data.cell.raw === 'TOTAL OPERATING EXP') {
        data.cell.styles.fontStyle = 'bold'; data.cell.styles.textColor = LIME
      }
      if (String(data.cell.raw).startsWith('✓')) data.cell.styles.textColor = LIME
    },
  })
  addPDFFooter(doc, businessName)
  doc.save('Expense-Budget.pdf')
}

export function generateExpenseBudgetExcel() {
  const data = [
    ['Expense Budget', `Generated: ${new Date().toLocaleDateString()}`],
    [],
    ['Category', 'Budget', 'Actual', 'Variance', 'Status'],
    ['Payroll & Benefits', 14500, 14500, 0, 'On Budget'],
    ['Rent & Utilities', 3200, 3200, 0, 'On Budget'],
    ['Software & Tools', 2000, 1800, 200, 'Under'],
    ['Marketing & Ads', 2500, 2100, 400, 'Under'],
    ['Insurance', 650, 650, 0, 'On Budget'],
    ['Travel & Entertainment', 500, 320, 180, 'Under'],
    ['Office Supplies', 300, 250, 50, 'Under'],
    ['Miscellaneous', 500, 250, 250, 'Under'],
    ['TOTAL', 24150, 23070, 1080, 'Under Budget'],
  ]
  makeXLSX(data, 'Expense Budget', 'Expense-Budget.xlsx', [28, 12, 12, 12, 14])
}

// ── AR Aging ──────────────────────────────────────────────────
export function generateARAgingPDF(businessName) {
  const doc = new jsPDF()
  addPDFHeader(doc, 'Accounts Receivable Aging', 'Current')
  doc.setFontSize(9); doc.setTextColor(...GREY)
  doc.text(`${businessName}   ·   Generated ${new Date().toLocaleDateString()}`, 10, 30)

  autoTable(doc, {
    startY: 36,
    head: [['Customer', 'Invoice #', 'Due Date', '0–30 Days', '31–60 Days', '61–90 Days', '90+ Days', 'Total']],
    body: [
      ['Acme Corp', 'INV-1041', '03/15/2026', '$8,500', '', '', '', '$8,500'],
      ['BuildRight LLC', 'INV-1039', '03/22/2026', '$6,200', '', '', '', '$6,200'],
      ['TechStart Inc', 'INV-1035', '02/28/2026', '', '$5,400', '', '', '$5,400'],
      ['Metro Services', 'INV-1030', '02/10/2026', '', '$1,800', '', '', '$1,800'],
      ['Pacific Foods', 'INV-1028', '02/05/2026', '', '', '$2,800', '', '$2,800'],
      ['Summit Co', 'INV-1025', '01/31/2026', '$3,800', '', '', '', '$3,800'],
      ['TOTAL', '', '', '$18,500', '$7,200', '$2,800', '$0', '$28,500'],
    ],
    ...tableStyles(),
    didParseCell(data) {
      if (data.cell.raw === 'TOTAL') {
        data.cell.styles.fontStyle = 'bold'; data.cell.styles.textColor = LIME
      }
    },
  })
  addPDFFooter(doc, businessName)
  doc.save('AR-Aging.pdf')
}

export function generateARAgingExcel() {
  const data = [
    ['AR Aging Report', `Generated: ${new Date().toLocaleDateString()}`],
    [],
    ['Customer', 'Invoice #', 'Due Date', '0-30 Days', '31-60 Days', '61-90 Days', '90+ Days', 'Total'],
    ['Acme Corp', 'INV-1041', '03/15/2026', 8500, '', '', '', 8500],
    ['BuildRight LLC', 'INV-1039', '03/22/2026', 6200, '', '', '', 6200],
    ['TechStart Inc', 'INV-1035', '02/28/2026', '', 5400, '', '', 5400],
    ['Metro Services', 'INV-1030', '02/10/2026', '', 1800, '', '', 1800],
    ['Pacific Foods', 'INV-1028', '02/05/2026', '', '', 2800, '', 2800],
    ['Summit Co', 'INV-1025', '01/31/2026', 3800, '', '', '', 3800],
    ['TOTAL', '', '', 18500, 7200, 2800, 0, 28500],
  ]
  makeXLSX(data, 'AR Aging', 'AR-Aging.xlsx', [20, 12, 14, 12, 12, 12, 12, 12])
}

// ── Break-Even Analysis ───────────────────────────────────────
export function generateBreakEvenPDF(businessName) {
  const doc = new jsPDF()
  const w = doc.internal.pageSize.getWidth()
  addPDFHeader(doc, 'Break-Even Analysis', 'Current Month')
  doc.setFontSize(9); doc.setTextColor(...GREY)
  doc.text(`${businessName}   ·   Generated ${new Date().toLocaleDateString()}`, 10, 30)

  // Summary cards
  const cards = [
    ['Fixed Costs / Month', '$22,500'],
    ['Variable Cost Ratio', '31%'],
    ['Break-Even Revenue', '$32,608'],
    ['Current Revenue', '$55,200'],
    ['Safety Margin', '69% above break-even'],
  ]
  doc.setFont('helvetica', 'bold'); doc.setFontSize(9); doc.setTextColor(...LIME)
  doc.text('KEY METRICS', 10, 38)
  cards.forEach(([label, val], i) => {
    const x = 10 + (i % 3) * 65
    const y = 42 + Math.floor(i / 3) * 22
    doc.setFillColor(...LGREY)
    doc.rect(x, y, 60, 18, 'F')
    doc.setFont('helvetica', 'normal'); doc.setFontSize(7); doc.setTextColor(...GREY)
    doc.text(label, x + 4, y + 7)
    doc.setFont('helvetica', 'bold'); doc.setFontSize(9); doc.setTextColor(...LIME)
    doc.text(val, x + 4, y + 14)
  })

  autoTable(doc, {
    startY: 90,
    head: [['Revenue Level', 'Fixed Costs', 'Variable Costs', 'Total Costs', 'Profit/Loss']],
    body: [
      ['$10,000', '$22,500', '$3,100', '$25,600', '-$15,600'],
      ['$20,000', '$22,500', '$6,200', '$28,700', '-$8,700'],
      ['$32,608 (Break-Even)', '$22,500', '$10,108', '$32,608', '$0'],
      ['$40,000', '$22,500', '$12,400', '$34,900', '+$5,100'],
      ['$55,200 (Current)', '$22,500', '$17,112', '$39,612', '+$15,588'],
      ['$70,000', '$22,500', '$21,700', '$44,200', '+$25,800'],
    ],
    ...tableStyles(),
    didParseCell(data) {
      if (String(data.cell.raw).includes('Break-Even')) {
        data.cell.styles.textColor = [255, 200, 0]
      }
      if (String(data.cell.raw).includes('Current')) {
        data.cell.styles.textColor = LIME; data.cell.styles.fontStyle = 'bold'
      }
      if (String(data.cell.raw).startsWith('-')) data.cell.styles.textColor = [255, 80, 80]
      if (String(data.cell.raw).startsWith('+')) data.cell.styles.textColor = LIME
    },
  })
  addPDFFooter(doc, businessName)
  doc.save('Break-Even-Analysis.pdf')
}

// ── Investor One-Pager ────────────────────────────────────────
export function generateInvestorOnePagerPDF(businessName, profile) {
  const doc = new jsPDF()
  const w = doc.internal.pageSize.getWidth()
  const h = doc.internal.pageSize.getHeight()

  // Full dark bg
  doc.setFillColor(...DARK)
  doc.rect(0, 0, w, h, 'F')

  // Header band
  doc.setFillColor(...LGREY)
  doc.rect(0, 0, w, 30, 'F')
  doc.setFillColor(...LIME)
  doc.rect(0, 0, w, 4, 'F')
  doc.setFont('helvetica', 'black'); doc.setFontSize(16); doc.setTextColor(...LIME)
  doc.text('CFO-X', 10, 20)
  doc.setFont('helvetica', 'bold'); doc.setFontSize(12); doc.setTextColor(...WHITE)
  doc.text(businessName.toUpperCase(), 36, 20)
  doc.setFont('helvetica', 'normal'); doc.setFontSize(8); doc.setTextColor(...GREY)
  doc.text('INVESTOR ONE-PAGER', w - 10, 20, { align: 'right' })

  // The Ask
  doc.setFillColor(...LIME)
  doc.rect(10, 35, w - 20, 18, 'F')
  doc.setFont('helvetica', 'bold'); doc.setFontSize(10); doc.setTextColor(...DARK)
  doc.text('THE ASK: $250,000 GROWTH ROUND', w / 2, 45, { align: 'center' })
  doc.setFontSize(8)
  doc.text('Revenue-based financing · 12-month term · No equity dilution', w / 2, 50, { align: 'center' })

  // 4 KPI boxes
  const kpis = [['$55,200', 'MRR'], ['26.2%', 'NET MARGIN'], ['+8.7%', 'MoM GROWTH'], ['25 MO', 'RUNWAY']]
  kpis.forEach(([val, label], i) => {
    const x = 10 + i * 48
    doc.setFillColor(...LGREY)
    doc.rect(x, 58, 44, 20, 'F')
    doc.setFont('helvetica', 'bold'); doc.setFontSize(11); doc.setTextColor(...LIME)
    doc.text(val, x + 22, 67, { align: 'center' })
    doc.setFont('helvetica', 'normal'); doc.setFontSize(6.5); doc.setTextColor(...GREY)
    doc.text(label, x + 22, 73, { align: 'center' })
  })

  // Business model
  doc.setFont('helvetica', 'bold'); doc.setFontSize(9); doc.setTextColor(...LIME)
  doc.text('BUSINESS MODEL', 10, 88)
  doc.setFont('helvetica', 'normal'); doc.setFontSize(8); doc.setTextColor(...WHITE)
  doc.text(`${businessName} operates in the ${profile?.industry || 'technology'} sector with a proven B2B revenue model. Product sales and recurring service contracts generate predictable cash flow with high margins.`, 10, 94, { maxWidth: w - 20 })

  // Traction
  doc.setFont('helvetica', 'bold'); doc.setFontSize(9); doc.setTextColor(...LIME)
  doc.text('TRACTION', 10, 110)
  const traction = [
    '• Revenue growing 8.7% month-over-month (3-month avg)',
    '• 26.2% net profit margin — above industry average',
    '• $47,000 cash on hand with zero credit card debt',
    '• AR pipeline of $28,500 across 6 active customers',
  ]
  doc.setFont('helvetica', 'normal'); doc.setFontSize(8); doc.setTextColor(...WHITE)
  traction.forEach((line, i) => doc.text(line, 10, 117 + i * 6))

  // Use of funds
  doc.setFont('helvetica', 'bold'); doc.setFontSize(9); doc.setTextColor(...LIME)
  doc.text('USE OF FUNDS', 10, 145)
  const funds = [
    ['Marketing & Acquisition', '$100,000', '40%'],
    ['Inventory & Operations', '$75,000', '30%'],
    ['Technology Infrastructure', '$50,000', '20%'],
    ['Working Capital Reserve', '$25,000', '10%'],
  ]
  autoTable(doc, {
    startY: 149,
    body: funds,
    ...tableStyles(),
    margin: { left: 10, right: 10 },
  })

  // Projections
  const y2 = doc.lastAutoTable.finalY + 8
  doc.setFont('helvetica', 'bold'); doc.setFontSize(9); doc.setTextColor(...LIME)
  doc.text('12-MONTH REVENUE PROJECTION', 10, y2)
  doc.setFont('helvetica', 'normal'); doc.setFontSize(8); doc.setTextColor(...WHITE)
  doc.text(`Conservative: $${Math.round(55200 * Math.pow(1.04, 12) / 1000)}K   Base: $${Math.round(55200 * Math.pow(1.087, 12) / 1000)}K   Optimistic: $${Math.round(55200 * Math.pow(1.14, 12) / 1000)}K`, 10, y2 + 7)

  // Footer
  doc.setFillColor(...LIME)
  doc.rect(0, h - 12, w, 12, 'F')
  doc.setFont('helvetica', 'bold'); doc.setFontSize(8); doc.setTextColor(...DARK)
  doc.text(`CONFIDENTIAL — ${businessName} · Generated by CFO-X · ${new Date().toLocaleDateString()}`, w / 2, h - 4, { align: 'center' })

  doc.save('Investor-One-Pager.pdf')
}

// ── 3-Year Financial Model (Excel) ────────────────────────────
export function generate3YearModelExcel(businessName) {
  const wb = XLSX.utils.book_new()

  // Sheet 1: Assumptions
  const assumptions = [
    ['3-YEAR FINANCIAL MODEL ASSUMPTIONS'],
    [`Business: ${businessName}`],
    [`Generated: ${new Date().toLocaleDateString()}`],
    [],
    ['GROWTH ASSUMPTIONS', 'Year 1', 'Year 2', 'Year 3'],
    ['Monthly Revenue Growth Rate', '8.7%', '7.0%', '5.5%'],
    ['Gross Margin Target', '69%', '70%', '71%'],
    ['Operating Expense Growth', '4.7%', '4.0%', '3.5%'],
    ['Customer Acquisition Cost', '$180', '$160', '$140'],
    ['Average Revenue Per Customer', '$920', '$980', '$1,050'],
    [],
    ['STARTING METRICS'],
    ['Current Monthly Revenue', 55200, '', ''],
    ['Current Monthly Expenses', 22500, '', ''],
    ['Current Net Margin', '26.2%', '', ''],
    ['Cash on Hand', 47000, '', ''],
  ]
  const ws1 = XLSX.utils.aoa_to_sheet(assumptions)
  ws1['!cols'] = [{ wch: 32 }, { wch: 14 }, { wch: 14 }, { wch: 14 }]
  XLSX.utils.book_append_sheet(wb, ws1, 'Assumptions')

  // Sheet 2: P&L Projection
  const months = Array.from({ length: 36 }, (_, i) => {
    const d = new Date(); d.setMonth(d.getMonth() + i + 1)
    return d.toLocaleDateString('en-US', { month: 'short', year: 'numeric' })
  })
  const plHeader = ['Month', 'Revenue', 'COGS', 'Gross Profit', 'OpEx', 'Net Profit', 'Net Margin']
  const plRows = months.map((m, i) => {
    const yr = Math.floor(i / 12)
    const rates = [0.087, 0.07, 0.055]
    const rev = Math.round(55200 * Math.pow(1 + rates[yr], i + 1))
    const cogs = Math.round(rev * 0.31)
    const gp = rev - cogs
    const opex = Math.round(22500 * Math.pow(1.047, i + 1))
    const net = gp - opex
    return [m, rev, cogs, gp, opex, net, `${((net / rev) * 100).toFixed(1)}%`]
  })
  const ws2 = XLSX.utils.aoa_to_sheet([plHeader, ...plRows])
  ws2['!cols'] = [{ wch: 16 }, ...Array(6).fill({ wch: 14 })]
  XLSX.utils.book_append_sheet(wb, ws2, 'P&L Projection')

  // Sheet 3: Cash Flow Projection
  const cfHeader = ['Month', 'Net Income', 'Depreciation', 'CapEx', 'Debt Service', 'Net Cash Flow', 'Cash Balance']
  let cashBal = 47000
  const cfRows = months.map((m, i) => {
    const yr = Math.floor(i / 12)
    const rates = [0.087, 0.07, 0.055]
    const rev = Math.round(55200 * Math.pow(1 + rates[yr], i + 1))
    const opex = Math.round(22500 * Math.pow(1.047, i + 1))
    const net = Math.round(rev * 0.69) - opex
    const dep = 750
    const capex = i % 12 === 0 ? -5000 : 0
    const debt = -1100
    const ncf = net + dep + capex + debt
    cashBal += ncf
    return [m, net, dep, capex, debt, ncf, cashBal]
  })
  const ws3 = XLSX.utils.aoa_to_sheet([cfHeader, ...cfRows])
  ws3['!cols'] = [{ wch: 16 }, ...Array(6).fill({ wch: 14 })]
  XLSX.utils.book_append_sheet(wb, ws3, 'Cash Flow Projection')

  // Sheet 4: Unit Economics
  const ueData = [
    ['UNIT ECONOMICS'],
    [],
    ['Metric', 'Current', 'Year 1 Target', 'Year 2 Target', 'Year 3 Target'],
    ['Monthly Revenue', 55200, 147000, 290000, 475000],
    ['Active Customers', 60, 159, 296, 452],
    ['ARPU (Monthly)', 920, 925, 980, 1050],
    ['Customer Acquisition Cost', 180, 160, 140, 120],
    ['Gross Margin', '69%', '69%', '70%', '71%'],
    ['LTV (12 mo)', 11040, 11100, 11760, 12600],
    ['LTV:CAC Ratio', '61.3x', '69.4x', '84.0x', '105x'],
    ['Monthly Churn Rate', '2.1%', '1.8%', '1.5%', '1.2%'],
    ['Net Revenue Retention', '108%', '112%', '115%', '118%'],
  ]
  const ws4 = XLSX.utils.aoa_to_sheet(ueData)
  ws4['!cols'] = [{ wch: 26 }, { wch: 14 }, { wch: 14 }, { wch: 14 }, { wch: 14 }]
  XLSX.utils.book_append_sheet(wb, ws4, 'Unit Economics')

  // Sheet 5: Scenarios
  const scenHeader = ['Year', 'Scenario', 'Annual Revenue', 'Annual Net Profit', 'Cumulative Cash']
  const scenRows = []
  for (let yr = 1; yr <= 3; yr++) {
    const scenarios = [
      ['Bear', 0.04], ['Base', 0.087], ['Bull', 0.14]
    ]
    scenarios.forEach(([name, rate]) => {
      const rev = Math.round(55200 * 12 * Math.pow(1 + rate, yr))
      const profit = Math.round(rev * 0.24)
      const cash = 47000 + profit * yr
      scenRows.push([`Year ${yr}`, name, rev, profit, cash])
    })
  }
  const ws5 = XLSX.utils.aoa_to_sheet([scenHeader, ...scenRows])
  ws5['!cols'] = [{ wch: 8 }, { wch: 10 }, { wch: 16 }, { wch: 18 }, { wch: 16 }]
  XLSX.utils.book_append_sheet(wb, ws5, 'Scenarios (Bear-Base-Bull)')

  XLSX.writeFile(wb, `3-Year-Financial-Model-${businessName.replace(/\s/g, '-')}.xlsx`)
}

// ── Helpers ───────────────────────────────────────────────────
function makeXLSX(data, sheetName, filename, colWidths = []) {
  const wb = XLSX.utils.book_new()
  const ws = XLSX.utils.aoa_to_sheet(data)
  if (colWidths.length) ws['!cols'] = colWidths.map(w => ({ wch: w }))
  XLSX.utils.book_append_sheet(wb, ws, sheetName)
  XLSX.writeFile(wb, filename)
}

function downloadText(content, filename, mime) {
  const blob = new Blob([content], { type: mime })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url; a.download = filename; a.click()
  URL.revokeObjectURL(url)
}

// ── Complete Package (ZIP via multiple downloads) ─────────────
export async function downloadCompletePackage(businessName, profile) {
  // Stagger downloads slightly so browsers don't block
  const fns = [
    () => generatePLPDF(businessName, '12 Months'),
    () => generateCashFlowPDF(businessName, '12 Months'),
    () => generateBalanceSheetPDF(businessName, 'Current'),
    () => generateExecutiveSummaryPDF(businessName, profile),
    () => generateProjectionsPDF(businessName),
    () => generateDebtSchedulePDF(businessName),
    () => generateExpenseBudgetPDF(businessName),
    () => generateARAgingPDF(businessName),
    () => generateBreakEvenPDF(businessName),
    () => generateInvestorOnePagerPDF(businessName, profile),
    () => generate3YearModelExcel(businessName),
  ]
  for (const fn of fns) {
    fn()
    await new Promise(r => setTimeout(r, 300))
  }
}
